sandbox = false

[import_mappings.customer]
address_as_str='Deliv Address'
contact_name='Deliv Contact'
email='Deliv Email'
delivery_name='Deliv Name'
postcode='Deliv Postcode'
telephone='Deliv Telephone'


[import_mappings.hire_sale]
shipment_name='Name'
address_as_str='Delivery Address'
contact_name='Delivery Contact'
email='Delivery Email'
delivery_name='Delivery Name'
postcode='Delivery Postcode'
telephone='Delivery Telephone'
customer='To Customer'
boxes='Boxes'
send_out_date='Send Out Date'
send_method='Send Method'
outbound_id='Outbound ID'
inbound_id='Inbound ID'


[home_contact]
name = 'Giles Toman'
email = 'radios@amherst.co.uk'
telephone = "0207 3289792"

[home_address]
address_id = 5536
dropoff_sender_id = 328187
dbay_key = 'NW64TE1003'
company_name = 'Amherst Radio Center'
street = '70 Kingsgate Road'
locality = 'Kilburn'
town_city = 'London'
county = "London"
postal_code = "NW6 4TE"
country_code = "GB"


[default_carrier.sandbox]
courier = 99
service = 9992


[default_carrier.production]
courier = 8  # parcelforce
service = 101  # parcelforce 24


[paths]
data = 'data/'
scripts = 'scripts/'
outbound_labels = 'data/Parcelforce Labels/outbound'
inbound_labels = 'data/Parcelforce Labels/inbound'
logfile = 'data/AmDesplog.txt'
